using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace Dreamer.AgentBridge
{
    /// <summary>
    /// Visual feedback for agents — render Unity assets to PNG so Claude can
    /// "see" what it's building. PreviewRenderUtility handles the off-screen
    /// scene/camera/lights setup; we frame the camera on the prefab's
    /// combined renderer bounds for an automatic best-effort thumbnail.
    /// </summary>
    public static class PreviewOps
    {
        // Screenshots live at the project root (not Library/) so they're
        // visible in VS Code's Explorer — Library/ is gitignored by default
        // and many editors / .vscode settings hide it. The folder ships with
        // a self-ignoring .gitignore so file contents stay out of source
        // control without requiring a project-level .gitignore edit.
        const string DefaultDir = "DreamerScreenshots";

        static void EnsureScreenshotDir()
        {
            if (!Directory.Exists(DefaultDir))
            {
                Directory.CreateDirectory(DefaultDir);
            }
            string giPath = Path.Combine(DefaultDir, ".gitignore");
            if (!File.Exists(giPath))
            {
                File.WriteAllText(giPath, "# Auto-generated by Dreamer screenshot commands.\n# Ignore PNGs and any other contents, but keep this .gitignore.\n*\n!.gitignore\n");
            }
        }

        // ─── screenshot-scene ─────────────────────────────────────────────

        public static CommandResult ScreenshotScene(Dictionary<string, object> args)
        {
            int width = SimpleJson.GetInt(args, "width", 1280);
            int height = SimpleJson.GetInt(args, "height", 720);
            if (width <= 0 || height <= 0)
                return CommandResult.Fail("'width' and 'height' must be positive.");
            if (width > 4096 || height > 4096)
                return CommandResult.Fail("'width' and 'height' max 4096.");

            string savePath = SimpleJson.GetString(args, "savePath");
            bool transparent = SimpleJson.GetBool(args, "transparent", false);
            if (!TryResolveBackground(args, transparent, new Color(0f, 0f, 0f, 1f), out Color background, out string bgErr))
                return CommandResult.Fail(bgErr);

            string cameraArg = SimpleJson.GetString(args, "camera");
            Camera cam = ResolveSceneCamera(cameraArg, out string camErr);
            if (cam == null) return CommandResult.Fail(camErr);

            // Default to Point — sharper than Unity's authored filter modes
            // (almost always Bilinear) and the right call for agent inspection
            // even in cases where Bilinear would technically blend better.
            // Pass --filter-mode bilinear / trilinear to override.
            string filterArg = SimpleJson.GetString(args, "filterMode");
            FilterMode? filterOverride;
            string filterErr;
            if (string.IsNullOrEmpty(filterArg))
            {
                filterOverride = FilterMode.Point;
                filterErr = null;
            }
            else if (!TryParseFilterMode(filterArg, out filterOverride, out filterErr))
            {
                return CommandResult.Fail(filterErr);
            }

            // ScreenSpaceOverlay canvases bypass cameras entirely — they draw
            // straight to the back buffer in a final compositing pass that
            // off-screen cam.Render() doesn't trigger. Temporarily flip them
            // to ScreenSpaceCamera bound to the render camera so they get
            // drawn into our RT, then restore on cleanup.
            var flipped = new List<(Canvas c, RenderMode mode, Camera worldCam, float planeDist)>();
            foreach (var canvas in UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None))
            {
                if (canvas == null || !canvas.enabled || !canvas.gameObject.activeInHierarchy) continue;
                if (canvas.renderMode == RenderMode.ScreenSpaceOverlay)
                {
                    flipped.Add((canvas, canvas.renderMode, canvas.worldCamera, canvas.planeDistance));
                    canvas.renderMode = RenderMode.ScreenSpaceCamera;
                    canvas.worldCamera = cam;
                    canvas.planeDistance = Mathf.Max(cam.nearClipPlane * 2f, 1f);
                }
            }
            // Force a layout pass after the flip so canvas geometry rebuilds
            // for the new camera context.
            Canvas.ForceUpdateCanvases();

            // Optional filter-mode swap on every UI source texture (Image,
            // RawImage, sprite atlases). Bilinear is Unity's UI default and
            // softens edges noticeably at non-1:1 scales — Point preserves
            // pixel-perfect crispness for stylized / pixel-art UI.
            var filterSwaps = filterOverride.HasValue ? SwizzleUITextureFilters(filterOverride.Value) : null;

            // No MSAA — we want pixel-accurate output, not anti-aliased.
            // Default RT antiAliasing inherits QualitySettings, which can
            // be 2/4/8 and softens hard edges via supersampling.
            var rt = RenderTexture.GetTemporary(width, height, 24, RenderTextureFormat.ARGB32, RenderTextureReadWrite.Default, 1);
            if (filterOverride.HasValue) rt.filterMode = filterOverride.Value;
            rt.Create();
            var prevTarget = cam.targetTexture;
            var prevActive = RenderTexture.active;
            var prevClearFlags = cam.clearFlags;
            var prevBackground = cam.backgroundColor;

            Texture2D rendered;
            try
            {
                cam.clearFlags = CameraClearFlags.SolidColor;
                cam.backgroundColor = background;
                cam.targetTexture = rt;
                RenderTexture.active = rt;
                GL.Clear(true, true, background);
                cam.Render();
                rendered = new Texture2D(width, height, TextureFormat.RGBA32, mipChain: false);
                rendered.ReadPixels(new Rect(0, 0, width, height), 0, 0);
                rendered.Apply();
            }
            finally
            {
                cam.clearFlags = prevClearFlags;
                cam.backgroundColor = prevBackground;
                cam.targetTexture = prevTarget;
                RenderTexture.active = prevActive;
                RenderTexture.ReleaseTemporary(rt);
                // Restore any flipped overlay canvases.
                foreach (var f in flipped)
                {
                    if (f.c == null) continue;
                    f.c.renderMode = f.mode;
                    f.c.worldCamera = f.worldCam;
                    f.c.planeDistance = f.planeDist;
                }
                // Restore source-texture filter modes.
                RestoreUITextureFilters(filterSwaps);
            }

            byte[] png = rendered.EncodeToPNG();
            UnityEngine.Object.DestroyImmediate(rendered);

            if (string.IsNullOrEmpty(savePath))
            {
                EnsureScreenshotDir();
                string camName = SanitizeFilename(cam.name);
                savePath = Path.Combine(DefaultDir, $"scene-{camName}-{DateTime.UtcNow.Ticks}.png").Replace('\\', '/');
            }
            else
            {
                string parent = Path.GetDirectoryName(savePath);
                if (!string.IsNullOrEmpty(parent)) Directory.CreateDirectory(parent);
            }

            File.WriteAllBytes(savePath, png);

            return CommandResult.Ok(SimpleJson.Object()
                .Put("camera", cam.name)
                .Put("path", savePath)
                .Put("width", width)
                .Put("height", height)
                .Put("byteCount", png.Length)
                .Put("flippedOverlayCanvases", flipped.Count)
                .Put("filterMode", filterOverride.HasValue ? filterOverride.Value.ToString() : "unchanged")
                .Put("textureFiltersSwapped", filterSwaps?.Count ?? 0)
                .Put("hint", "Open the PNG with the Read tool to view the rendered scene.")
                .ToString());
        }

        static Camera ResolveSceneCamera(string path, out string error)
        {
            error = null;
            if (string.IsNullOrEmpty(path))
            {
                var main = Camera.main;
                if (main != null) return main;
                var any = UnityEngine.Object.FindFirstObjectByType<Camera>();
                if (any == null)
                {
                    error = "No active Camera found in the active scene. Specify --camera, or ensure a Camera GameObject exists.";
                    return null;
                }
                return any;
            }
            // Try by name first (handles "Main Camera"), then by scene path.
            foreach (var c in UnityEngine.Object.FindObjectsByType<Camera>(FindObjectsSortMode.None))
            {
                if (c == null) continue;
                if (string.Equals(c.name, path, StringComparison.Ordinal)) return c;
            }
            var go = PropertyOps.FindSceneObject(path, out string findErr);
            if (go == null)
            {
                error = $"Camera not found: '{path}'. Tried name match and scene path. {findErr ?? ""}";
                return null;
            }
            var cam = go.GetComponent<Camera>();
            if (cam == null)
            {
                error = $"GameObject at '{path}' has no Camera component.";
                return null;
            }
            return cam;
        }

        static bool TryParseFilterMode(string s, out FilterMode? mode, out string error)
        {
            mode = null;
            error = null;
            if (string.IsNullOrEmpty(s)) return true; // unset → no override
            switch (s.Trim().ToLowerInvariant())
            {
                case "point":     mode = FilterMode.Point; return true;
                case "bilinear":  mode = FilterMode.Bilinear; return true;
                case "trilinear": mode = FilterMode.Trilinear; return true;
                default:
                    error = $"filterMode must be 'point', 'bilinear', or 'trilinear'; got '{s}'.";
                    return false;
            }
        }

        static List<(Texture tex, FilterMode original)> SwizzleUITextureFilters(FilterMode newMode)
        {
            // Override every UI source texture's filterMode for the duration
            // of this render. Bilinear (the Unity default) softens edges at
            // non-1:1 scales — Point preserves pixel-perfect detail. We
            // dedupe by Texture instance (multiple Images often share an
            // atlas) and restore originals in the finally block.
            var swaps = new List<(Texture, FilterMode)>();
            var seen = new HashSet<Texture>();

            void Track(Texture tex)
            {
                if (tex == null || !seen.Add(tex)) return;
                swaps.Add((tex, tex.filterMode));
                tex.filterMode = newMode;
            }

            foreach (var img in UnityEngine.Object.FindObjectsByType<Image>(FindObjectsSortMode.None))
            {
                if (img == null) continue;
                Track(img.mainTexture);
                if (img.sprite != null) Track(img.sprite.texture);
            }
            foreach (var raw in UnityEngine.Object.FindObjectsByType<RawImage>(FindObjectsSortMode.None))
            {
                if (raw == null) continue;
                Track(raw.mainTexture);
                Track(raw.texture);
            }
            foreach (var sr in UnityEngine.Object.FindObjectsByType<SpriteRenderer>(FindObjectsSortMode.None))
            {
                if (sr == null || sr.sprite == null) continue;
                Track(sr.sprite.texture);
            }
            return swaps;
        }

        static void RestoreUITextureFilters(List<(Texture tex, FilterMode original)> swaps)
        {
            if (swaps == null) return;
            foreach (var s in swaps)
            {
                if (s.tex == null) continue;
                s.tex.filterMode = s.original;
            }
        }

        static string SanitizeFilename(string s)
        {
            if (string.IsNullOrEmpty(s)) return "camera";
            var sb = new System.Text.StringBuilder(s.Length);
            foreach (var c in s) sb.Append(char.IsLetterOrDigit(c) || c == '_' || c == '-' ? c : '_');
            return sb.ToString();
        }

        static bool TryResolveBackground(Dictionary<string, object> args, bool transparent, Color defaultColor, out Color color, out string error)
        {
            error = null;
            if (transparent) { color = new Color(0f, 0f, 0f, 0f); return true; }
            if (args.TryGetValue("backgroundColor", out object bgObj))
                return TryParseColor(bgObj, out color, out error);
            color = defaultColor;
            return true;
        }

        // ─── screenshot-prefab ────────────────────────────────────────────

        public static CommandResult ScreenshotPrefab(Dictionary<string, object> args)
        {
            string assetPath = AssetOps.ResolveAssetPath(args);
            if (assetPath == null)
                return CommandResult.Fail("Provide 'assetPath' or 'guid' (path to a prefab).");
            if (!assetPath.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase))
                return CommandResult.Fail($"'{assetPath}' is not a .prefab. screenshot-prefab only handles GameObject prefabs; use a future preview-asset for materials/sprites.");

            int width = SimpleJson.GetInt(args, "width", 512);
            int height = SimpleJson.GetInt(args, "height", 512);
            if (width <= 0 || height <= 0)
                return CommandResult.Fail("'width' and 'height' must be positive.");
            if (width > 4096 || height > 4096)
                return CommandResult.Fail("'width' and 'height' max 4096.");

            string savePath = SimpleJson.GetString(args, "savePath");
            string angleArg = SimpleJson.GetString(args, "angle");
            string angle = angleArg ?? "iso";
            bool angleExplicit = !string.IsNullOrEmpty(angleArg);

            // Optional UI-mode size override: --size [w,h] sets the prefab
            // RectTransform's sizeDelta after instantiation. Useful for prefabs
            // that are designed to be sized by a parent layout group at runtime
            // and have zero/tiny size in standalone form.
            Vector2? sizeOverride = null;
            if (args.TryGetValue("size", out object sizeObj) && sizeObj is List<object> sizeArr && sizeArr.Count >= 2)
            {
                sizeOverride = new Vector2(ToFloat(sizeArr[0]), ToFloat(sizeArr[1]));
            }
            bool transparent = SimpleJson.GetBool(args, "transparent", false);
            Color background;
            if (transparent)
            {
                background = new Color(0f, 0f, 0f, 0f);
            }
            else if (args.TryGetValue("backgroundColor", out object bgObj))
            {
                if (!TryParseColor(bgObj, out background, out string colorErr))
                    return CommandResult.Fail(colorErr);
            }
            else
            {
                background = new Color(0.32f, 0.32f, 0.36f, 1f);
            }

            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            if (prefab == null)
                return CommandResult.Fail($"Failed to load prefab at '{assetPath}'.");

            PreviewRenderUtility pru = null;
            GameObject instance = null;
            GameObject wrapperCanvasGO = null;
            try
            {
                pru = new PreviewRenderUtility();

                pru.camera.clearFlags = CameraClearFlags.SolidColor;
                pru.camera.backgroundColor = background;
                // Transparent backgrounds need the camera to use a render
                // target with an alpha channel — PreviewRenderUtility's
                // internal RT is ARGB32 by default, so EncodeToPNG below
                // preserves alpha. If the resulting PNG is opaque despite
                // alpha=0, the platform's preview RT format isn't ARGB32
                // and we'd need a custom RT (not done here yet).
                pru.camera.allowHDR = false;
                pru.camera.fieldOfView = 30f;
                pru.camera.nearClipPlane = 0.05f;
                pru.camera.farClipPlane = 5000f;
                // Render everything — PreviewRenderUtility's default culling
                // mask excludes most layers, so UI prefabs (layer 5) and
                // anything else outside the default come back invisible.
                pru.camera.cullingMask = ~0;

                // Two-light rim setup — key from upper-front, fill from lower-back.
                if (pru.lights != null && pru.lights.Length >= 2)
                {
                    pru.lights[0].intensity = 1.2f;
                    pru.lights[0].transform.rotation = Quaternion.Euler(35f, 35f, 0f);
                    pru.lights[1].intensity = 0.55f;
                    pru.lights[1].transform.rotation = Quaternion.Euler(-25f, -160f, 0f);
                }
                pru.ambientColor = new Color(0.28f, 0.28f, 0.32f);

                // Spawn the prefab. Stay in the active scene initially so the
                // Canvas rebuild / LayoutRebuilder pipeline runs (these only
                // tick on real scenes — PRU's preview scene is a stripped-down
                // context where Canvas geometry doesn't get built).
                instance = UnityEngine.Object.Instantiate(prefab);
                instance.hideFlags = HideFlags.HideAndDontSave;

                Canvas rootCanvas = FindCanvas(instance);
                bool isFragment = rootCanvas == null && IsUIFragment(instance);
                bool uiMode = rootCanvas != null || isFragment;

                if (isFragment)
                {
                    // Wrap the fragment in a temporary WorldSpace canvas so it
                    // has a render target. Layout-group-driven prefabs come
                    // back at their authored size — usually small or zero —
                    // so we also resize the prefab's RectTransform here.
                    wrapperCanvasGO = CreateWrappingCanvas();
                    var wrapperRT = wrapperCanvasGO.GetComponent<RectTransform>();
                    instance.transform.SetParent(wrapperCanvasGO.transform, worldPositionStays: false);
                    SizeFragment(instance, sizeOverride);
                    rootCanvas = wrapperCanvasGO.GetComponent<Canvas>();
                }

                if (uiMode)
                {
                    var setupRoot = isFragment ? wrapperCanvasGO : instance;
                    SetupCanvasForPreview(setupRoot, rootCanvas, pru.camera);
                    if (!angleExplicit) angle = "front";
                }

                // For 3D mode, move into PRU's preview scene. UI mode renders
                // via a temp camera in the active scene (PRU's preview scene
                // doesn't run the Canvas mesh-build pipeline), so we leave
                // the instance in the active scene.
                if (!uiMode) pru.AddSingleGO(instance);

                // Frame the camera on combined bounds.
                GameObject uiRoot = isFragment ? wrapperCanvasGO : instance;
                Bounds bounds = uiMode ? ComputeUIBounds(uiRoot) : ComputeBounds(instance);
                Vector3 dirLocal = AngleToCameraDir(angle);
                if (uiMode)
                {
                    // UI canvases render their visible face on the -Z side of
                    // the rect transform (matches Unity's Scene-view default
                    // — drag a canvas into the scene and its text reads
                    // correctly when the editor camera looks down +Z toward
                    // the canvas at origin). AngleToCameraDir's "front" already
                    // returns Vector3.back which puts the camera at -Z looking
                    // +Z, so no flip is needed.

                    // Orthographic camera framed on the UI's world-corner extent.
                    pru.camera.orthographic = true;
                    pru.camera.orthographicSize = Mathf.Max(bounds.extents.y, bounds.extents.x * (float)height / Mathf.Max(width, 1), 1f);
                    float dist = Mathf.Max(bounds.extents.z + 100f, 200f);
                    pru.camera.transform.position = bounds.center + dirLocal.normalized * dist;
                    pru.camera.transform.LookAt(bounds.center);
                    pru.camera.nearClipPlane = 0.01f;
                    pru.camera.farClipPlane = dist * 4f;
                }
                else
                {
                    pru.camera.orthographic = false;
                    float radius = Mathf.Max(bounds.extents.magnitude, 0.5f);
                    float distance = radius / Mathf.Sin(pru.camera.fieldOfView * 0.5f * Mathf.Deg2Rad);
                    pru.camera.transform.position = bounds.center + dirLocal.normalized * distance * 1.35f;
                    pru.camera.transform.LookAt(bounds.center);
                }

                // Render off-screen → Texture2D. Use a custom ARGB32 RT instead
                // of PreviewRenderUtility.BeginStaticPreview / EndStaticPreview:
                // the latter allocates an RGB-only RT internally, so an alpha=0
                // background would silently come back as solid black. Using our
                // own ARGB32 RT preserves the alpha channel through to PNG.
                Texture2D rendered;
                if (uiMode)
                {
                    // PreviewRenderUtility's preview scene doesn't run the
                    // Canvas/CanvasRenderer mesh-build pipeline, so UI prefabs
                    // come back invisible no matter what we do with pru.camera.
                    // Workaround: render via a temporary camera in the active
                    // scene, with the prefab parked off-screen briefly. We
                    // reset all the temporary state in the finally block.
                    rendered = RenderUIOffscreen(uiRoot, rootCanvas, width, height, background, dirLocal, bounds);
                }
                else
                {
                    var rt = RenderTexture.GetTemporary(width, height, 24, RenderTextureFormat.ARGB32);
                    rt.Create();
                    var prevTarget = pru.camera.targetTexture;
                    var prevActive = RenderTexture.active;
                    try
                    {
                        pru.camera.targetTexture = rt;
                        RenderTexture.active = rt;
                        GL.Clear(true, true, background);
                        pru.camera.Render();
                        rendered = new Texture2D(width, height, TextureFormat.RGBA32, mipChain: false);
                        rendered.ReadPixels(new Rect(0, 0, width, height), 0, 0);
                        rendered.Apply();
                    }
                    finally
                    {
                        RenderTexture.active = prevActive;
                        pru.camera.targetTexture = prevTarget;
                        RenderTexture.ReleaseTemporary(rt);
                    }
                }

                if (rendered == null)
                    return CommandResult.Fail("Render returned null. Likely cause: graphics device unavailable (headless/batch mode without -nographics workaround), or Unity is unfocused on a platform that throttles render.");

                byte[] png = rendered.EncodeToPNG();
                UnityEngine.Object.DestroyImmediate(rendered);

                if (string.IsNullOrEmpty(savePath))
                {
                    EnsureScreenshotDir();
                    string assetGuid = AssetDatabase.AssetPathToGUID(assetPath);
                    string stem = Path.GetFileNameWithoutExtension(assetPath);
                    savePath = Path.Combine(DefaultDir, $"{stem}-{assetGuid.Substring(0, 8)}-{DateTime.UtcNow.Ticks}.png").Replace('\\', '/');
                }
                else
                {
                    string parent = Path.GetDirectoryName(savePath);
                    if (!string.IsNullOrEmpty(parent)) Directory.CreateDirectory(parent);
                }

                File.WriteAllBytes(savePath, png);

                var resultJson = SimpleJson.Object()
                    .Put("asset", assetPath)
                    .Put("path", savePath)
                    .Put("width", width)
                    .Put("height", height)
                    .Put("byteCount", png.Length)
                    .Put("angle", angle)
                    .Put("mode", uiMode ? "ui" : "3d")
                    .PutRaw("boundsCenter", $"[{bounds.center.x},{bounds.center.y},{bounds.center.z}]")
                    .PutRaw("boundsSize", $"[{bounds.size.x},{bounds.size.y},{bounds.size.z}]");

                if (uiMode)
                {
                    int graphicCount = 0;
                    int activeGraphicCount = 0;
                    int totalVertices = 0;
                    foreach (var g in instance.GetComponentsInChildren<Graphic>(includeInactive: true))
                    {
                        graphicCount++;
                        if (g.enabled && g.gameObject.activeInHierarchy) activeGraphicCount++;
                        var cr = g.canvasRenderer;
                        if (cr != null) totalVertices += cr.relativeDepth >= 0 ? 0 : 0; // CanvasRenderer doesn't expose vertex count directly; placeholder
                    }
                    resultJson
                        .Put("uiCanvasRenderMode", rootCanvas.renderMode.ToString())
                        .Put("uiCanvasWorldCameraSet", rootCanvas.worldCamera != null)
                        .Put("uiGraphicCount", graphicCount)
                        .Put("uiActiveGraphicCount", activeGraphicCount)
                        .Put("uiCullingMask", pru.camera.cullingMask)
                        .Put("uiCameraOrtho", pru.camera.orthographic)
                        .Put("uiCameraOrthoSize", pru.camera.orthographicSize)
                        .PutRaw("uiCameraPos", $"[{pru.camera.transform.position.x},{pru.camera.transform.position.y},{pru.camera.transform.position.z}]")
                        .Put("uiInstanceLayer", instance.layer);
                }

                resultJson.Put("hint", "Open the PNG with the Read tool to view the rendered prefab.");
                return CommandResult.Ok(resultJson.ToString());
            }
            catch (Exception ex)
            {
                return CommandResult.Fail($"Screenshot failed: {ex.GetType().Name}: {ex.Message}");
            }
            finally
            {
                // Destroy wrapper first — if instance is parented under it,
                // DestroyImmediate(wrapper) takes the instance with it.
                if (wrapperCanvasGO != null) UnityEngine.Object.DestroyImmediate(wrapperCanvasGO);
                if (instance != null && instance) UnityEngine.Object.DestroyImmediate(instance);
                if (pru != null) pru.Cleanup();
            }
        }

        // ── Helpers ───────────────────────────────────────────────────────

        static Bounds ComputeBounds(GameObject root)
        {
            // Compute from mesh data, NOT from Renderer.bounds. Renderer.bounds
            // is initialized lazily by the rendering pipeline and comes back
            // (0,0,0) for objects in a PreviewScene that haven't been rendered
            // yet — which is exactly our case (we compute bounds before the
            // first Render() to know where to place the camera).
            Bounds? combined = null;

            foreach (var mf in root.GetComponentsInChildren<MeshFilter>(includeInactive: true))
            {
                if (mf == null || mf.sharedMesh == null) continue;
                var w = TransformBounds(mf.sharedMesh.bounds, mf.transform.localToWorldMatrix);
                combined = combined.HasValue ? Encapsulate(combined.Value, w) : w;
            }

            foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>(includeInactive: true))
            {
                if (smr == null || smr.sharedMesh == null) continue;
                // SkinnedMeshRenderer.localBounds is the asset's bind-pose extent.
                var w = TransformBounds(smr.localBounds, smr.transform.localToWorldMatrix);
                combined = combined.HasValue ? Encapsulate(combined.Value, w) : w;
            }

            foreach (var sr in root.GetComponentsInChildren<SpriteRenderer>(includeInactive: true))
            {
                if (sr == null || sr.sprite == null) continue;
                var w = TransformBounds(sr.sprite.bounds, sr.transform.localToWorldMatrix);
                combined = combined.HasValue ? Encapsulate(combined.Value, w) : w;
            }

            // ParticleSystemRenderer / TrailRenderer / LineRenderer rarely have
            // a useful pre-render extent — skip them; their bounds are dynamic.

            if (combined.HasValue && combined.Value.size != Vector3.zero)
                return combined.Value;

            // No mesh-bearing renderers — union child transforms as a coarse
            // proxy (works for empty containers, lights-only prefabs, etc).
            var transforms = root.GetComponentsInChildren<Transform>(includeInactive: true);
            Bounds tb = new Bounds(root.transform.position, Vector3.one);
            foreach (var t in transforms) tb.Encapsulate(t.position);
            return tb;
        }

        static Bounds TransformBounds(Bounds local, Matrix4x4 m)
        {
            // AABB transform: new extents pick up rotation/scale via |m_ij| sums.
            var center = m.MultiplyPoint3x4(local.center);
            var ext = local.extents;
            var newExt = new Vector3(
                Mathf.Abs(m.m00) * ext.x + Mathf.Abs(m.m01) * ext.y + Mathf.Abs(m.m02) * ext.z,
                Mathf.Abs(m.m10) * ext.x + Mathf.Abs(m.m11) * ext.y + Mathf.Abs(m.m12) * ext.z,
                Mathf.Abs(m.m20) * ext.x + Mathf.Abs(m.m21) * ext.y + Mathf.Abs(m.m22) * ext.z
            );
            return new Bounds(center, newExt * 2f);
        }

        static Bounds Encapsulate(Bounds a, Bounds b) { a.Encapsulate(b); return a; }

        // ── UI / Canvas mode ─────────────────────────────────────────────

        static bool IsUIFragment(GameObject root)
        {
            // A "UI fragment" is a prefab that uses uGUI components but doesn't
            // wrap them in its own Canvas — typically a list-item / row / button
            // meant to be parented under an existing Canvas at runtime. We can
            // still render it by wrapping in a temporary Canvas of our own.
            if (root.GetComponent<RectTransform>() == null) return false;
            if (root.GetComponent<Graphic>() != null) return true;
            if (root.GetComponentInChildren<Graphic>(includeInactive: true) != null) return true;
            // Also accept LayoutElement-only roots — sometimes a fragment is
            // a wrapper with LayoutElement and the Graphics live in children.
            if (root.GetComponent<LayoutElement>() != null) return true;
            return false;
        }

        static GameObject CreateWrappingCanvas()
        {
            var go = new GameObject("DreamerPreviewWrapperCanvas");
            go.hideFlags = HideFlags.HideAndDontSave;
            go.transform.position = Vector3.zero;
            var canvas = go.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;
            canvas.sortingOrder = 0;
            // CanvasScaler in ConstantPixelSize keeps the world-space units
            // matching pixels, so a 200×80 RectTransform sizeDelta means
            // 200×80 world units — predictable framing.
            var scaler = go.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ConstantPixelSize;
            scaler.scaleFactor = 1f;
            // Give the wrapping canvas RT a generous size — children can
            // anchor however they want, the camera frames the actual content
            // bounds (not the canvas rect).
            var rt = go.GetComponent<RectTransform>();
            if (rt != null) rt.sizeDelta = new Vector2(2000f, 2000f);
            return go;
        }

        static void SizeFragment(GameObject instance, Vector2? sizeOverride)
        {
            var rt = instance.GetComponent<RectTransform>();
            if (rt == null) return;

            // Explicit override always wins.
            if (sizeOverride.HasValue)
            {
                rt.sizeDelta = sizeOverride.Value;
                rt.anchorMin = new Vector2(0.5f, 0.5f);
                rt.anchorMax = new Vector2(0.5f, 0.5f);
                rt.anchoredPosition = Vector2.zero;
                return;
            }

            // Use LayoutElement preferred/min hints if the prefab has them.
            var le = instance.GetComponent<LayoutElement>();
            Vector2 size = rt.sizeDelta;
            if (le != null)
            {
                if (le.preferredWidth > 0) size.x = le.preferredWidth;
                else if (le.minWidth > 0) size.x = le.minWidth;
                if (le.preferredHeight > 0) size.y = le.preferredHeight;
                else if (le.minHeight > 0) size.y = le.minHeight;
            }
            // Fallback for genuinely zero-sized prefabs (no hints, no authored
            // size). 400×100 is a plausible "list item" footprint that fits
            // most fragments without being silly.
            if (size.x < 1f) size.x = 400f;
            if (size.y < 1f) size.y = 100f;

            rt.sizeDelta = size;
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = Vector2.zero;
        }

        static Canvas FindCanvas(GameObject root)
        {
            var c = root.GetComponent<Canvas>();
            if (c != null) return c;
            // Some prefabs nest a Canvas one level deep (a "PageRoot" with a
            // Canvas child). Pick the topmost-found Canvas — we don't try to
            // synthesize a wrapping Canvas for prefabs that have none, since
            // those are usually fragments meant to be parented under an
            // existing Canvas, not standalone screens.
            return root.GetComponentInChildren<Canvas>(includeInactive: true);
        }

        static void SetupCanvasForPreview(GameObject root, Canvas canvas, Camera previewCamera)
        {
            // World-space rendering binds to a specific camera. Without this,
            // ScreenSpaceOverlay draws directly to the screen and Camera.Render
            // never sees the canvas.
            canvas.renderMode = RenderMode.WorldSpace;
            canvas.worldCamera = previewCamera;
            canvas.sortingOrder = 0;

            // Reset transform — prefab may have a non-zero position/rotation.
            root.transform.position = Vector3.zero;
            root.transform.rotation = Quaternion.identity;
            root.transform.localScale = Vector3.one;

            // Lock the CanvasScaler to constant pixel size so the layout pass
            // produces a predictable extent. ScaleWithScreenSize would scale
            // by the (irrelevant) preview RT dimensions vs reference resolution.
            var scaler = canvas.GetComponent<CanvasScaler>();
            if (scaler != null)
            {
                scaler.uiScaleMode = CanvasScaler.ScaleMode.ConstantPixelSize;
                scaler.scaleFactor = 1f;
            }

            // Force a full layout rebuild — instantiated prefabs come back
            // with zero-sized RectTransforms until the LayoutRebuilder runs.
            Canvas.ForceUpdateCanvases();
            foreach (var rt in root.GetComponentsInChildren<RectTransform>(includeInactive: true))
            {
                LayoutRebuilder.ForceRebuildLayoutImmediate(rt);
            }
            // Force every Graphic to rebuild its CanvasRenderer mesh — disabling
            // and re-enabling triggers OnDisable/OnEnable which mark the mesh
            // dirty. Without this, nested Graphics often render as zero-vertex.
            foreach (var g in root.GetComponentsInChildren<Graphic>(includeInactive: true))
            {
                if (g == null) continue;
                g.SetAllDirty();
            }
            // TextMeshPro has its own mesh-build pipeline that doesn't tick
            // from Canvas.ForceUpdateCanvases — it relies on a per-frame
            // OnPreRenderText callback, which doesn't fire in our preview
            // path. Reach into TMP via reflection to call ForceMeshUpdate()
            // on each TMP component, which forces an immediate mesh build.
            // Reflection avoids a hard package dependency on com.unity.textmeshpro.
            ForceTMPMeshUpdate(root);
            Canvas.ForceUpdateCanvases();
        }

        static MethodInfo _tmpForceMeshUpdateCached;
        static Type _tmpTextBaseTypeCached;
        static bool _tmpReflectionResolved;

        static void ForceTMPMeshUpdate(GameObject root)
        {
            // Resolve TMP_Text + ForceMeshUpdate once. If the project doesn't
            // have TMP installed, both stay null and we skip every call cheaply.
            if (!_tmpReflectionResolved)
            {
                _tmpReflectionResolved = true;
                foreach (var asm in System.AppDomain.CurrentDomain.GetAssemblies())
                {
                    var t = asm.GetType("TMPro.TMP_Text", throwOnError: false);
                    if (t != null)
                    {
                        _tmpTextBaseTypeCached = t;
                        // ForceMeshUpdate() — parameterless overload triggers
                        // the immediate rebuild we want.
                        _tmpForceMeshUpdateCached = t.GetMethod("ForceMeshUpdate", Type.EmptyTypes);
                        break;
                    }
                }
            }
            if (_tmpTextBaseTypeCached == null || _tmpForceMeshUpdateCached == null) return;

            // GetComponentsInChildren typed by base TMP_Text catches both
            // TextMeshProUGUI (Canvas) and TextMeshPro (3D) subclasses.
            var components = root.GetComponentsInChildren(_tmpTextBaseTypeCached, includeInactive: true);
            foreach (var c in components)
            {
                if (c == null) continue;
                try { _tmpForceMeshUpdateCached.Invoke(c, null); }
                catch (Exception) { /* one bad TMP component shouldn't kill the screenshot */ }
            }
        }

        static Texture2D RenderUIOffscreen(GameObject instance, Canvas rootCanvas, int width, int height, Color background, Vector3 dirLocal, Bounds bounds)
        {
            // Park the canvas at a far-off position so it doesn't interfere
            // with the visible scene if user happens to be looking at the
            // editor. Canvas world position is preserved via parent transform —
            // we offset by adding to the root, render, then the caller's
            // finally block destroys the instance.
            var offset = new Vector3(0f, 0f, -100000f);
            instance.transform.position += offset;
            var offsetCenter = bounds.center + offset;

            // Temp camera GameObject in the active scene. HideFlags so it
            // doesn't appear in the user's hierarchy / get saved.
            var camGO = new GameObject("DreamerPreviewCamera");
            camGO.hideFlags = HideFlags.HideAndDontSave;
            var cam = camGO.AddComponent<Camera>();
            cam.cullingMask = ~0;
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = background;
            cam.orthographic = true;
            cam.orthographicSize = Mathf.Max(bounds.extents.y, bounds.extents.x * (float)height / Mathf.Max(width, 1), 1f);
            cam.nearClipPlane = 0.01f;
            float dist = Mathf.Max(bounds.extents.z + 100f, 200f);
            cam.farClipPlane = dist * 4f;
            cam.transform.position = offsetCenter + dirLocal.normalized * dist;
            cam.transform.LookAt(offsetCenter);
            cam.allowHDR = false;
            cam.allowMSAA = true;
            cam.enabled = false; // we'll call Render() manually

            // Bind canvas to this temp camera too, so it knows where to submit.
            rootCanvas.worldCamera = cam;

            var rt = RenderTexture.GetTemporary(width, height, 24, RenderTextureFormat.ARGB32);
            rt.Create();
            var prevTarget = cam.targetTexture;
            var prevActive = RenderTexture.active;
            Texture2D rendered;
            try
            {
                cam.targetTexture = rt;
                RenderTexture.active = rt;
                GL.Clear(true, true, background);
                Canvas.ForceUpdateCanvases();
                cam.Render();
                rendered = new Texture2D(width, height, TextureFormat.RGBA32, mipChain: false);
                rendered.ReadPixels(new Rect(0, 0, width, height), 0, 0);
                rendered.Apply();
            }
            finally
            {
                RenderTexture.active = prevActive;
                cam.targetTexture = prevTarget;
                RenderTexture.ReleaseTemporary(rt);
                UnityEngine.Object.DestroyImmediate(camGO);
                instance.transform.position -= offset;
            }
            return rendered;
        }

        static Bounds ComputeUIBounds(GameObject root)
        {
            // Take the union of every visible UI Graphic's world-space rect.
            // RectTransform.GetWorldCorners yields the four corners after the
            // layout pass. Disabled/inactive elements are excluded so the camera
            // doesn't frame off-screen panels invisibly extending the bounds.
            var corners = new Vector3[4];
            Bounds? combined = null;

            foreach (var graphic in root.GetComponentsInChildren<Graphic>(includeInactive: false))
            {
                if (graphic == null || !graphic.enabled) continue;
                var rt = graphic.rectTransform;
                if (rt == null) continue;
                rt.GetWorldCorners(corners);
                Bounds b = new Bounds(corners[0], Vector3.zero);
                for (int i = 1; i < 4; i++) b.Encapsulate(corners[i]);
                if (b.size.x < 0.01f && b.size.y < 0.01f) continue; // skip zero-sized
                combined = combined.HasValue ? Encapsulate(combined.Value, b) : b;
            }

            if (combined.HasValue && combined.Value.size != Vector3.zero)
                return combined.Value;

            // Fallback to the canvas's own RectTransform if no Graphics found.
            var rootRT = root.GetComponent<RectTransform>();
            if (rootRT != null)
            {
                rootRT.GetWorldCorners(corners);
                Bounds b = new Bounds(corners[0], Vector3.zero);
                for (int i = 1; i < 4; i++) b.Encapsulate(corners[i]);
                if (b.size != Vector3.zero) return b;
            }
            return new Bounds(root.transform.position, Vector3.one);
        }

        static bool TryParseColor(object raw, out Color color, out string error)
        {
            color = Color.black;
            error = null;
            if (raw is string s)
            {
                s = s.Trim();
                if (s.StartsWith("#")) s = s.Substring(1);
                if (s.Length == 6 || s.Length == 8)
                {
                    try
                    {
                        byte r = Convert.ToByte(s.Substring(0, 2), 16);
                        byte g = Convert.ToByte(s.Substring(2, 2), 16);
                        byte b = Convert.ToByte(s.Substring(4, 2), 16);
                        byte a = (s.Length == 8) ? Convert.ToByte(s.Substring(6, 2), 16) : (byte)255;
                        color = new Color32(r, g, b, a);
                        return true;
                    }
                    catch (Exception ex)
                    {
                        error = $"Hex color parse failed: {ex.Message}";
                        return false;
                    }
                }
                error = $"Hex color must be #RRGGBB or #RRGGBBAA; got '{s}'.";
                return false;
            }
            if (raw is List<object> arr && (arr.Count == 3 || arr.Count == 4))
            {
                color = new Color(
                    ToFloat(arr[0]),
                    ToFloat(arr[1]),
                    ToFloat(arr[2]),
                    arr.Count == 4 ? ToFloat(arr[3]) : 1f);
                return true;
            }
            error = "backgroundColor must be a hex string (#RRGGBB or #RRGGBBAA) or an RGB(A) array of 0..1 floats.";
            return false;
        }

        static float ToFloat(object o)
        {
            if (o is double d) return (float)d;
            if (o is float f) return f;
            if (o is long l) return l;
            if (o is int i) return i;
            return 0f;
        }

        static Vector3 AngleToCameraDir(string angle)
        {
            switch ((angle ?? "iso").Trim().ToLowerInvariant())
            {
                case "front":   return Quaternion.Euler(0f, 0f, 0f) * Vector3.back;
                case "back":    return Quaternion.Euler(0f, 180f, 0f) * Vector3.back;
                case "side":
                case "right":   return Quaternion.Euler(0f, 90f, 0f) * Vector3.back;
                case "left":    return Quaternion.Euler(0f, -90f, 0f) * Vector3.back;
                case "top":     return Quaternion.Euler(89f, 0f, 0f) * Vector3.back;
                case "bottom":  return Quaternion.Euler(-89f, 0f, 0f) * Vector3.back;
                case "iso":
                default:        return Quaternion.Euler(20f, -30f, 0f) * Vector3.back;
            }
        }
    }
}
