using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace Dreamer.AgentBridge
{
    /// <summary>Render Unity assets/scenes to PNG so agents can "see" what they're building.</summary>
    public static class PreviewOps
    {
        // Screenshots live at the project root (not Library/) so they're visible in
        // editors that hide Library/. The folder ships a self-ignoring .gitignore.
        const string DefaultDir = "DreamerScreenshots";

        static void EnsureScreenshotDir()
        {
            if (!Directory.Exists(DefaultDir))
            {
                Directory.CreateDirectory(DefaultDir);
            }
            string giPath = Path.Combine(DefaultDir, ".gitignore");
            if (!File.Exists(giPath))
            {
                File.WriteAllText(giPath, "# Auto-generated by Dreamer screenshot commands.\n# Ignore PNGs and any other contents, but keep this .gitignore.\n*\n!.gitignore\n");
            }
        }

        // ─── screenshot-scene ─────────────────────────────────────────────

        public static CommandResult ScreenshotScene(Dictionary<string, object> args)
        {
            int width = SimpleJson.GetInt(args, "width", 1280);
            int height = SimpleJson.GetInt(args, "height", 720);
            if (width <= 0 || height <= 0)
                return CommandResult.Fail("'width' and 'height' must be positive.");
            if (width > 4096 || height > 4096)
                return CommandResult.Fail("'width' and 'height' max 4096.");

            string savePath = SimpleJson.GetString(args, "savePath");
            bool transparent = SimpleJson.GetBool(args, "transparent", false);
            if (!TryResolveBackground(args, transparent, new Color(0f, 0f, 0f, 1f), out Color background, out string bgErr))
                return CommandResult.Fail(bgErr);

            string cameraArg = SimpleJson.GetString(args, "camera");
            Camera cam = ResolveSceneCamera(cameraArg, out string camErr);
            if (cam == null) return CommandResult.Fail(camErr);

            // Default to Point — sharper than Bilinear (Unity's UI default) for agent inspection.
            string filterArg = SimpleJson.GetString(args, "filterMode");
            FilterMode? filterOverride;
            string filterErr;
            if (string.IsNullOrEmpty(filterArg))
            {
                filterOverride = FilterMode.Point;
                filterErr = null;
            }
            else if (!TryParseFilterMode(filterArg, out filterOverride, out filterErr))
            {
                return CommandResult.Fail(filterErr);
            }

            // ScreenSpaceOverlay canvases bypass cameras (final back-buffer compositing pass that
            // off-screen cam.Render() doesn't trigger). Flip to ScreenSpaceCamera, restore on cleanup.
            var flipped = new List<(Canvas c, RenderMode mode, Camera worldCam, float planeDist)>();
            foreach (var canvas in UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None))
            {
                if (canvas == null || !canvas.enabled || !canvas.gameObject.activeInHierarchy) continue;
                if (canvas.renderMode == RenderMode.ScreenSpaceOverlay)
                {
                    flipped.Add((canvas, canvas.renderMode, canvas.worldCamera, canvas.planeDistance));
                    canvas.renderMode = RenderMode.ScreenSpaceCamera;
                    canvas.worldCamera = cam;
                    canvas.planeDistance = Mathf.Max(cam.nearClipPlane * 2f, 1f);
                }
            }
            // Layout pass after the flip so canvas geometry rebuilds for the new camera context.
            Canvas.ForceUpdateCanvases();

            // Swap UI texture filter modes (Image/RawImage/SpriteRenderer share atlases). Default Bilinear
            // softens edges; Point preserves pixel-perfect crispness for stylized/pixel-art UI.
            var filterSwaps = filterOverride.HasValue ? SwizzleUITextureFilters(filterOverride.Value) : null;

            // antiAliasing=1 — default inherits QualitySettings (2/4/8) which softens hard edges.
            var rt = RenderTexture.GetTemporary(width, height, 24, RenderTextureFormat.ARGB32, RenderTextureReadWrite.Default, 1);
            if (filterOverride.HasValue) rt.filterMode = filterOverride.Value;
            rt.Create();
            var prevTarget = cam.targetTexture;
            var prevActive = RenderTexture.active;
            var prevClearFlags = cam.clearFlags;
            var prevBackground = cam.backgroundColor;

            Texture2D rendered;
            try
            {
                cam.clearFlags = CameraClearFlags.SolidColor;
                cam.backgroundColor = background;
                cam.targetTexture = rt;
                RenderTexture.active = rt;
                GL.Clear(true, true, background);
                cam.Render();
                rendered = new Texture2D(width, height, TextureFormat.RGBA32, mipChain: false);
                rendered.ReadPixels(new Rect(0, 0, width, height), 0, 0);
                rendered.Apply();
            }
            finally
            {
                cam.clearFlags = prevClearFlags;
                cam.backgroundColor = prevBackground;
                cam.targetTexture = prevTarget;
                RenderTexture.active = prevActive;
                RenderTexture.ReleaseTemporary(rt);
                foreach (var f in flipped)
                {
                    if (f.c == null) continue;
                    f.c.renderMode = f.mode;
                    f.c.worldCamera = f.worldCam;
                    f.c.planeDistance = f.planeDist;
                }
                RestoreUITextureFilters(filterSwaps);
            }

            byte[] png = rendered.EncodeToPNG();
            UnityEngine.Object.DestroyImmediate(rendered);

            if (string.IsNullOrEmpty(savePath))
            {
                EnsureScreenshotDir();
                string camName = SanitizeFilename(cam.name);
                savePath = Path.Combine(DefaultDir, $"scene-{camName}-{DateTime.UtcNow.Ticks}.png").Replace('\\', '/');
            }
            else
            {
                string parent = Path.GetDirectoryName(savePath);
                if (!string.IsNullOrEmpty(parent)) Directory.CreateDirectory(parent);
            }

            File.WriteAllBytes(savePath, png);

            return CommandResult.Ok(SimpleJson.Object()
                .Put("camera", cam.name)
                .Put("path", savePath)
                .Put("width", width)
                .Put("height", height)
                .Put("byteCount", png.Length)
                .Put("flippedOverlayCanvases", flipped.Count)
                .Put("filterMode", filterOverride.HasValue ? filterOverride.Value.ToString() : "unchanged")
                .Put("textureFiltersSwapped", filterSwaps?.Count ?? 0)
                .Put("hint", "Open the PNG with the Read tool to view the rendered scene.")
                .ToString());
        }

        static Camera ResolveSceneCamera(string path, out string error)
        {
            error = null;
            if (string.IsNullOrEmpty(path))
            {
                var main = Camera.main;
                if (main != null) return main;
                var any = UnityEngine.Object.FindFirstObjectByType<Camera>();
                if (any == null)
                {
                    error = "No active Camera found in the active scene. Specify --camera, or ensure a Camera GameObject exists.";
                    return null;
                }
                return any;
            }
            // Name match first (handles "Main Camera"), then scene path.
            foreach (var c in UnityEngine.Object.FindObjectsByType<Camera>(FindObjectsSortMode.None))
            {
                if (c == null) continue;
                if (string.Equals(c.name, path, StringComparison.Ordinal)) return c;
            }
            var go = PropertyOps.FindSceneObject(path, out string findErr);
            if (go == null)
            {
                error = $"Camera not found: '{path}'. Tried name match and scene path. {findErr ?? ""}";
                return null;
            }
            var cam = go.GetComponent<Camera>();
            if (cam == null)
            {
                error = $"GameObject at '{path}' has no Camera component.";
                return null;
            }
            return cam;
        }

        static bool TryParseFilterMode(string s, out FilterMode? mode, out string error)
        {
            mode = null;
            error = null;
            if (string.IsNullOrEmpty(s)) return true;
            switch (s.Trim().ToLowerInvariant())
            {
                case "point":     mode = FilterMode.Point; return true;
                case "bilinear":  mode = FilterMode.Bilinear; return true;
                case "trilinear": mode = FilterMode.Trilinear; return true;
                default:
                    error = $"filterMode must be 'point', 'bilinear', or 'trilinear'; got '{s}'.";
                    return false;
            }
        }

        // Override every UI source texture's filterMode; dedupe by Texture (atlases shared across Images).
        static List<(Texture tex, FilterMode original)> SwizzleUITextureFilters(FilterMode newMode)
        {
            var swaps = new List<(Texture, FilterMode)>();
            var seen = new HashSet<Texture>();

            void Track(Texture tex)
            {
                if (tex == null || !seen.Add(tex)) return;
                swaps.Add((tex, tex.filterMode));
                tex.filterMode = newMode;
            }

            foreach (var img in UnityEngine.Object.FindObjectsByType<Image>(FindObjectsSortMode.None))
            {
                if (img == null) continue;
                Track(img.mainTexture);
                if (img.sprite != null) Track(img.sprite.texture);
            }
            foreach (var raw in UnityEngine.Object.FindObjectsByType<RawImage>(FindObjectsSortMode.None))
            {
                if (raw == null) continue;
                Track(raw.mainTexture);
                Track(raw.texture);
            }
            foreach (var sr in UnityEngine.Object.FindObjectsByType<SpriteRenderer>(FindObjectsSortMode.None))
            {
                if (sr == null || sr.sprite == null) continue;
                Track(sr.sprite.texture);
            }
            return swaps;
        }

        static void RestoreUITextureFilters(List<(Texture tex, FilterMode original)> swaps)
        {
            if (swaps == null) return;
            foreach (var s in swaps)
            {
                if (s.tex == null) continue;
                s.tex.filterMode = s.original;
            }
        }

        static string SanitizeFilename(string s)
        {
            if (string.IsNullOrEmpty(s)) return "camera";
            var sb = new System.Text.StringBuilder(s.Length);
            foreach (var c in s) sb.Append(char.IsLetterOrDigit(c) || c == '_' || c == '-' ? c : '_');
            return sb.ToString();
        }

        static bool TryResolveBackground(Dictionary<string, object> args, bool transparent, Color defaultColor, out Color color, out string error)
        {
            error = null;
            if (transparent) { color = new Color(0f, 0f, 0f, 0f); return true; }
            if (args.TryGetValue("backgroundColor", out object bgObj))
                return TryParseColor(bgObj, out color, out error);
            color = defaultColor;
            return true;
        }

        // ─── screenshot-prefab ────────────────────────────────────────────

        public static CommandResult ScreenshotPrefab(Dictionary<string, object> args)
        {
            string assetPath = AssetOps.ResolveAssetPath(args);
            if (assetPath == null)
                return CommandResult.Fail("Provide 'assetPath' or 'guid' (path to a prefab).");
            if (!assetPath.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase))
                return CommandResult.Fail($"'{assetPath}' is not a .prefab. screenshot-prefab only handles GameObject prefabs; use a future preview-asset for materials/sprites.");

            int width = SimpleJson.GetInt(args, "width", 512);
            int height = SimpleJson.GetInt(args, "height", 512);
            if (width <= 0 || height <= 0)
                return CommandResult.Fail("'width' and 'height' must be positive.");
            if (width > 4096 || height > 4096)
                return CommandResult.Fail("'width' and 'height' max 4096.");

            string savePath = SimpleJson.GetString(args, "savePath");
            string angleArg = SimpleJson.GetString(args, "angle");
            string angle = angleArg ?? "iso";
            bool angleExplicit = !string.IsNullOrEmpty(angleArg);

            // --size sets the prefab RectTransform's sizeDelta — useful for prefabs sized by a
            // runtime layout group that come back zero/tiny in standalone form.
            Vector2? sizeOverride = null;
            if (args.TryGetValue("size", out object sizeObj) && sizeObj is List<object> sizeArr && sizeArr.Count >= 2)
            {
                sizeOverride = new Vector2(ToFloat(sizeArr[0]), ToFloat(sizeArr[1]));
            }
            bool transparent = SimpleJson.GetBool(args, "transparent", false);
            Color background;
            if (transparent)
            {
                background = new Color(0f, 0f, 0f, 0f);
            }
            else if (args.TryGetValue("backgroundColor", out object bgObj))
            {
                if (!TryParseColor(bgObj, out background, out string colorErr))
                    return CommandResult.Fail(colorErr);
            }
            else
            {
                background = new Color(0.32f, 0.32f, 0.36f, 1f);
            }

            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            if (prefab == null)
                return CommandResult.Fail($"Failed to load prefab at '{assetPath}'.");

            PreviewRenderUtility pru = null;
            GameObject instance = null;
            GameObject wrapperCanvasGO = null;
            try
            {
                pru = new PreviewRenderUtility();

                pru.camera.clearFlags = CameraClearFlags.SolidColor;
                pru.camera.backgroundColor = background;
                pru.camera.allowHDR = false;
                pru.camera.fieldOfView = 30f;
                pru.camera.nearClipPlane = 0.05f;
                pru.camera.farClipPlane = 5000f;
                // PRU's default culling mask excludes most layers — UI (5) and others come back invisible.
                pru.camera.cullingMask = ~0;

                // Two-light rim setup — key from upper-front, fill from lower-back.
                if (pru.lights != null && pru.lights.Length >= 2)
                {
                    pru.lights[0].intensity = 1.2f;
                    pru.lights[0].transform.rotation = Quaternion.Euler(35f, 35f, 0f);
                    pru.lights[1].intensity = 0.55f;
                    pru.lights[1].transform.rotation = Quaternion.Euler(-25f, -160f, 0f);
                }
                pru.ambientColor = new Color(0.28f, 0.28f, 0.32f);

                // Spawn in the active scene so Canvas rebuild / LayoutRebuilder ticks — PRU's
                // preview scene is stripped-down and Canvas geometry doesn't build there.
                instance = UnityEngine.Object.Instantiate(prefab);
                instance.hideFlags = HideFlags.HideAndDontSave;

                Canvas rootCanvas = FindCanvas(instance);
                bool isFragment = rootCanvas == null && IsUIFragment(instance);
                bool uiMode = rootCanvas != null || isFragment;

                if (isFragment)
                {
                    // Wrap the fragment in a temporary WorldSpace canvas. Layout-group-driven prefabs
                    // come back at their authored size (usually zero/tiny) so SizeFragment handles that.
                    wrapperCanvasGO = CreateWrappingCanvas();
                    var wrapperRT = wrapperCanvasGO.GetComponent<RectTransform>();
                    instance.transform.SetParent(wrapperCanvasGO.transform, worldPositionStays: false);
                    SizeFragment(instance, sizeOverride);
                    rootCanvas = wrapperCanvasGO.GetComponent<Canvas>();
                }

                if (uiMode)
                {
                    var setupRoot = isFragment ? wrapperCanvasGO : instance;
                    SetupCanvasForPreview(setupRoot, rootCanvas, pru.camera);
                    if (!angleExplicit) angle = "front";
                }

                // 3D mode → PRU's preview scene. UI mode → temp camera in active scene
                // (PRU's preview scene doesn't run the Canvas mesh-build pipeline).
                if (!uiMode) pru.AddSingleGO(instance);

                GameObject uiRoot = isFragment ? wrapperCanvasGO : instance;
                Bounds bounds = uiMode ? ComputeUIBounds(uiRoot) : ComputeBounds(instance);
                Vector3 dirLocal = AngleToCameraDir(angle);
                if (uiMode)
                {
                    // Orthographic camera framed on the UI's world-corner extent. UI canvases render
                    // their visible face on -Z; AngleToCameraDir's "front" already places camera at -Z.
                    pru.camera.orthographic = true;
                    pru.camera.orthographicSize = Mathf.Max(bounds.extents.y, bounds.extents.x * (float)height / Mathf.Max(width, 1), 1f);
                    float dist = Mathf.Max(bounds.extents.z + 100f, 200f);
                    pru.camera.transform.position = bounds.center + dirLocal.normalized * dist;
                    pru.camera.transform.LookAt(bounds.center);
                    pru.camera.nearClipPlane = 0.01f;
                    pru.camera.farClipPlane = dist * 4f;
                }
                else
                {
                    pru.camera.orthographic = false;
                    float radius = Mathf.Max(bounds.extents.magnitude, 0.5f);
                    float distance = radius / Mathf.Sin(pru.camera.fieldOfView * 0.5f * Mathf.Deg2Rad);
                    pru.camera.transform.position = bounds.center + dirLocal.normalized * distance * 1.35f;
                    pru.camera.transform.LookAt(bounds.center);
                }

                // Custom ARGB32 RT (not BeginStaticPreview, which uses RGB-only and silently
                // turns alpha=0 into solid black). UI mode uses a temp camera in the active scene
                // because PRU's preview scene doesn't run the Canvas/CanvasRenderer mesh-build pipeline.
                Texture2D rendered;
                if (uiMode)
                {
                    rendered = RenderUIOffscreen(uiRoot, rootCanvas, width, height, background, dirLocal, bounds);
                }
                else
                {
                    var rt = RenderTexture.GetTemporary(width, height, 24, RenderTextureFormat.ARGB32);
                    rt.Create();
                    var prevTarget = pru.camera.targetTexture;
                    var prevActive = RenderTexture.active;
                    try
                    {
                        pru.camera.targetTexture = rt;
                        RenderTexture.active = rt;
                        GL.Clear(true, true, background);
                        pru.camera.Render();
                        rendered = new Texture2D(width, height, TextureFormat.RGBA32, mipChain: false);
                        rendered.ReadPixels(new Rect(0, 0, width, height), 0, 0);
                        rendered.Apply();
                    }
                    finally
                    {
                        RenderTexture.active = prevActive;
                        pru.camera.targetTexture = prevTarget;
                        RenderTexture.ReleaseTemporary(rt);
                    }
                }

                if (rendered == null)
                    return CommandResult.Fail("Render returned null. Likely cause: graphics device unavailable (headless/batch mode without -nographics workaround), or Unity is unfocused on a platform that throttles render.");

                byte[] png = rendered.EncodeToPNG();
                UnityEngine.Object.DestroyImmediate(rendered);

                if (string.IsNullOrEmpty(savePath))
                {
                    EnsureScreenshotDir();
                    string assetGuid = AssetDatabase.AssetPathToGUID(assetPath);
                    string stem = Path.GetFileNameWithoutExtension(assetPath);
                    savePath = Path.Combine(DefaultDir, $"{stem}-{assetGuid.Substring(0, 8)}-{DateTime.UtcNow.Ticks}.png").Replace('\\', '/');
                }
                else
                {
                    string parent = Path.GetDirectoryName(savePath);
                    if (!string.IsNullOrEmpty(parent)) Directory.CreateDirectory(parent);
                }

                File.WriteAllBytes(savePath, png);

                var resultJson = SimpleJson.Object()
                    .Put("asset", assetPath)
                    .Put("path", savePath)
                    .Put("width", width)
                    .Put("height", height)
                    .Put("byteCount", png.Length)
                    .Put("angle", angle)
                    .Put("mode", uiMode ? "ui" : "3d")
                    .PutRaw("boundsCenter", $"[{bounds.center.x},{bounds.center.y},{bounds.center.z}]")
                    .PutRaw("boundsSize", $"[{bounds.size.x},{bounds.size.y},{bounds.size.z}]");

                if (uiMode)
                {
                    int graphicCount = 0;
                    int activeGraphicCount = 0;
                    int totalVertices = 0;
                    foreach (var g in instance.GetComponentsInChildren<Graphic>(includeInactive: true))
                    {
                        graphicCount++;
                        if (g.enabled && g.gameObject.activeInHierarchy) activeGraphicCount++;
                        var cr = g.canvasRenderer;
                        if (cr != null) totalVertices += cr.relativeDepth >= 0 ? 0 : 0; // CanvasRenderer doesn't expose vertex count directly; placeholder
                    }
                    resultJson
                        .Put("uiCanvasRenderMode", rootCanvas.renderMode.ToString())
                        .Put("uiCanvasWorldCameraSet", rootCanvas.worldCamera != null)
                        .Put("uiGraphicCount", graphicCount)
                        .Put("uiActiveGraphicCount", activeGraphicCount)
                        .Put("uiCullingMask", pru.camera.cullingMask)
                        .Put("uiCameraOrtho", pru.camera.orthographic)
                        .Put("uiCameraOrthoSize", pru.camera.orthographicSize)
                        .PutRaw("uiCameraPos", $"[{pru.camera.transform.position.x},{pru.camera.transform.position.y},{pru.camera.transform.position.z}]")
                        .Put("uiInstanceLayer", instance.layer);
                }

                resultJson.Put("hint", "Open the PNG with the Read tool to view the rendered prefab.");
                return CommandResult.Ok(resultJson.ToString());
            }
            catch (Exception ex)
            {
                return CommandResult.Fail($"Screenshot failed: {ex.GetType().Name}: {ex.Message}");
            }
            finally
            {
                // Destroy wrapper first — instance parented under it gets taken with DestroyImmediate(wrapper).
                if (wrapperCanvasGO != null) UnityEngine.Object.DestroyImmediate(wrapperCanvasGO);
                if (instance != null && instance) UnityEngine.Object.DestroyImmediate(instance);
                if (pru != null) pru.Cleanup();
            }
        }

        // ── Helpers ───────────────────────────────────────────────────────

        // Compute from mesh data, NOT Renderer.bounds — the latter is lazily initialized
        // and reports (0,0,0) for un-rendered PreviewScene objects (our case here).
        static Bounds ComputeBounds(GameObject root)
        {
            Bounds? combined = null;

            foreach (var mf in root.GetComponentsInChildren<MeshFilter>(includeInactive: true))
            {
                if (mf == null || mf.sharedMesh == null) continue;
                var w = TransformBounds(mf.sharedMesh.bounds, mf.transform.localToWorldMatrix);
                combined = combined.HasValue ? Encapsulate(combined.Value, w) : w;
            }

            foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>(includeInactive: true))
            {
                if (smr == null || smr.sharedMesh == null) continue;
                var w = TransformBounds(smr.localBounds, smr.transform.localToWorldMatrix);
                combined = combined.HasValue ? Encapsulate(combined.Value, w) : w;
            }

            foreach (var sr in root.GetComponentsInChildren<SpriteRenderer>(includeInactive: true))
            {
                if (sr == null || sr.sprite == null) continue;
                var w = TransformBounds(sr.sprite.bounds, sr.transform.localToWorldMatrix);
                combined = combined.HasValue ? Encapsulate(combined.Value, w) : w;
            }

            // Skip ParticleSystem/Trail/LineRenderer — their bounds are dynamic with no useful pre-render extent.
            if (combined.HasValue && combined.Value.size != Vector3.zero)
                return combined.Value;

            // No mesh renderers — coarse fallback for empty containers / lights-only prefabs.
            var transforms = root.GetComponentsInChildren<Transform>(includeInactive: true);
            Bounds tb = new Bounds(root.transform.position, Vector3.one);
            foreach (var t in transforms) tb.Encapsulate(t.position);
            return tb;
        }

        // AABB transform: new extents pick up rotation/scale via |m_ij| sums.
        static Bounds TransformBounds(Bounds local, Matrix4x4 m)
        {
            var center = m.MultiplyPoint3x4(local.center);
            var ext = local.extents;
            var newExt = new Vector3(
                Mathf.Abs(m.m00) * ext.x + Mathf.Abs(m.m01) * ext.y + Mathf.Abs(m.m02) * ext.z,
                Mathf.Abs(m.m10) * ext.x + Mathf.Abs(m.m11) * ext.y + Mathf.Abs(m.m12) * ext.z,
                Mathf.Abs(m.m20) * ext.x + Mathf.Abs(m.m21) * ext.y + Mathf.Abs(m.m22) * ext.z
            );
            return new Bounds(center, newExt * 2f);
        }

        static Bounds Encapsulate(Bounds a, Bounds b) { a.Encapsulate(b); return a; }

        // ── UI / Canvas mode ─────────────────────────────────────────────

        // A "UI fragment" uses uGUI but has no own Canvas — list items, rows, buttons meant to be
        // parented under an existing Canvas at runtime. We render by wrapping in a temp Canvas.
        static bool IsUIFragment(GameObject root)
        {
            if (root.GetComponent<RectTransform>() == null) return false;
            if (root.GetComponent<Graphic>() != null) return true;
            if (root.GetComponentInChildren<Graphic>(includeInactive: true) != null) return true;
            if (root.GetComponent<LayoutElement>() != null) return true;
            return false;
        }

        static GameObject CreateWrappingCanvas()
        {
            var go = new GameObject("DreamerPreviewWrapperCanvas");
            go.hideFlags = HideFlags.HideAndDontSave;
            go.transform.position = Vector3.zero;
            var canvas = go.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.WorldSpace;
            canvas.sortingOrder = 0;
            // ConstantPixelSize keeps world units == pixels, so sizeDelta maps directly to framing.
            var scaler = go.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ConstantPixelSize;
            scaler.scaleFactor = 1f;
            var rt = go.GetComponent<RectTransform>();
            if (rt != null) rt.sizeDelta = new Vector2(2000f, 2000f);
            return go;
        }

        static void SizeFragment(GameObject instance, Vector2? sizeOverride)
        {
            var rt = instance.GetComponent<RectTransform>();
            if (rt == null) return;

            if (sizeOverride.HasValue)
            {
                rt.sizeDelta = sizeOverride.Value;
                rt.anchorMin = new Vector2(0.5f, 0.5f);
                rt.anchorMax = new Vector2(0.5f, 0.5f);
                rt.anchoredPosition = Vector2.zero;
                return;
            }

            var le = instance.GetComponent<LayoutElement>();
            Vector2 size = rt.sizeDelta;
            if (le != null)
            {
                if (le.preferredWidth > 0) size.x = le.preferredWidth;
                else if (le.minWidth > 0) size.x = le.minWidth;
                if (le.preferredHeight > 0) size.y = le.preferredHeight;
                else if (le.minHeight > 0) size.y = le.minHeight;
            }
            // 400×100 — plausible "list item" footprint for genuinely zero-sized prefabs.
            if (size.x < 1f) size.x = 400f;
            if (size.y < 1f) size.y = 100f;

            rt.sizeDelta = size;
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = Vector2.zero;
        }

        static Canvas FindCanvas(GameObject root)
        {
            var c = root.GetComponent<Canvas>();
            if (c != null) return c;
            return root.GetComponentInChildren<Canvas>(includeInactive: true);
        }

        static void SetupCanvasForPreview(GameObject root, Canvas canvas, Camera previewCamera)
        {
            // WorldSpace + worldCamera binding. ScreenSpaceOverlay draws straight to the screen
            // and Camera.Render() never sees the canvas.
            canvas.renderMode = RenderMode.WorldSpace;
            canvas.worldCamera = previewCamera;
            canvas.sortingOrder = 0;

            root.transform.position = Vector3.zero;
            root.transform.rotation = Quaternion.identity;
            root.transform.localScale = Vector3.one;

            // ConstantPixelSize gives a predictable layout-pass extent; ScaleWithScreenSize would
            // scale against the (irrelevant) preview RT dimensions.
            var scaler = canvas.GetComponent<CanvasScaler>();
            if (scaler != null)
            {
                scaler.uiScaleMode = CanvasScaler.ScaleMode.ConstantPixelSize;
                scaler.scaleFactor = 1f;
            }

            // Instantiated prefabs come back with zero-sized RectTransforms until LayoutRebuilder runs.
            Canvas.ForceUpdateCanvases();
            foreach (var rt in root.GetComponentsInChildren<RectTransform>(includeInactive: true))
            {
                LayoutRebuilder.ForceRebuildLayoutImmediate(rt);
            }
            // SetAllDirty forces CanvasRenderer mesh rebuild — without this, nested Graphics often
            // render zero-vertex.
            foreach (var g in root.GetComponentsInChildren<Graphic>(includeInactive: true))
            {
                if (g == null) continue;
                g.SetAllDirty();
            }
            // TMP's mesh-build pipeline runs from a per-frame OnPreRenderText callback that doesn't
            // fire in this preview path; ForceMeshUpdate via reflection avoids a hard TMP dependency.
            ForceTMPMeshUpdate(root);
            Canvas.ForceUpdateCanvases();
        }

        static MethodInfo _tmpForceMeshUpdateCached;
        static Type _tmpTextBaseTypeCached;
        static bool _tmpReflectionResolved;

        static void ForceTMPMeshUpdate(GameObject root)
        {
            // Resolved once; nulls if TMP isn't installed (cheap skip per call).
            if (!_tmpReflectionResolved)
            {
                _tmpReflectionResolved = true;
                foreach (var asm in System.AppDomain.CurrentDomain.GetAssemblies())
                {
                    var t = asm.GetType("TMPro.TMP_Text", throwOnError: false);
                    if (t != null)
                    {
                        _tmpTextBaseTypeCached = t;
                        _tmpForceMeshUpdateCached = t.GetMethod("ForceMeshUpdate", Type.EmptyTypes);
                        break;
                    }
                }
            }
            if (_tmpTextBaseTypeCached == null || _tmpForceMeshUpdateCached == null) return;

            // Base TMP_Text catches both TextMeshProUGUI (Canvas) and TextMeshPro (3D).
            var components = root.GetComponentsInChildren(_tmpTextBaseTypeCached, includeInactive: true);
            foreach (var c in components)
            {
                if (c == null) continue;
                try { _tmpForceMeshUpdateCached.Invoke(c, null); }
                catch (Exception) { /* one bad TMP component shouldn't kill the screenshot */ }
            }
        }

        static Texture2D RenderUIOffscreen(GameObject instance, Canvas rootCanvas, int width, int height, Color background, Vector3 dirLocal, Bounds bounds)
        {
            // Park the canvas far off so it doesn't interfere with the visible scene during render.
            var offset = new Vector3(0f, 0f, -100000f);
            instance.transform.position += offset;
            var offsetCenter = bounds.center + offset;

            var camGO = new GameObject("DreamerPreviewCamera");
            camGO.hideFlags = HideFlags.HideAndDontSave;
            var cam = camGO.AddComponent<Camera>();
            cam.cullingMask = ~0;
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = background;
            cam.orthographic = true;
            cam.orthographicSize = Mathf.Max(bounds.extents.y, bounds.extents.x * (float)height / Mathf.Max(width, 1), 1f);
            cam.nearClipPlane = 0.01f;
            float dist = Mathf.Max(bounds.extents.z + 100f, 200f);
            cam.farClipPlane = dist * 4f;
            cam.transform.position = offsetCenter + dirLocal.normalized * dist;
            cam.transform.LookAt(offsetCenter);
            cam.allowHDR = false;
            cam.allowMSAA = true;
            cam.enabled = false;

            rootCanvas.worldCamera = cam;

            var rt = RenderTexture.GetTemporary(width, height, 24, RenderTextureFormat.ARGB32);
            rt.Create();
            var prevTarget = cam.targetTexture;
            var prevActive = RenderTexture.active;
            Texture2D rendered;
            try
            {
                cam.targetTexture = rt;
                RenderTexture.active = rt;
                GL.Clear(true, true, background);
                Canvas.ForceUpdateCanvases();
                cam.Render();
                rendered = new Texture2D(width, height, TextureFormat.RGBA32, mipChain: false);
                rendered.ReadPixels(new Rect(0, 0, width, height), 0, 0);
                rendered.Apply();
            }
            finally
            {
                RenderTexture.active = prevActive;
                cam.targetTexture = prevTarget;
                RenderTexture.ReleaseTemporary(rt);
                UnityEngine.Object.DestroyImmediate(camGO);
                instance.transform.position -= offset;
            }
            return rendered;
        }

        // Union of visible Graphics' world-corner rects after the layout pass; excludes
        // disabled/inactive so off-screen panels don't invisibly extend bounds.
        static Bounds ComputeUIBounds(GameObject root)
        {
            var corners = new Vector3[4];
            Bounds? combined = null;

            foreach (var graphic in root.GetComponentsInChildren<Graphic>(includeInactive: false))
            {
                if (graphic == null || !graphic.enabled) continue;
                var rt = graphic.rectTransform;
                if (rt == null) continue;
                rt.GetWorldCorners(corners);
                Bounds b = new Bounds(corners[0], Vector3.zero);
                for (int i = 1; i < 4; i++) b.Encapsulate(corners[i]);
                if (b.size.x < 0.01f && b.size.y < 0.01f) continue;
                combined = combined.HasValue ? Encapsulate(combined.Value, b) : b;
            }

            if (combined.HasValue && combined.Value.size != Vector3.zero)
                return combined.Value;

            var rootRT = root.GetComponent<RectTransform>();
            if (rootRT != null)
            {
                rootRT.GetWorldCorners(corners);
                Bounds b = new Bounds(corners[0], Vector3.zero);
                for (int i = 1; i < 4; i++) b.Encapsulate(corners[i]);
                if (b.size != Vector3.zero) return b;
            }
            return new Bounds(root.transform.position, Vector3.one);
        }

        static bool TryParseColor(object raw, out Color color, out string error)
        {
            color = Color.black;
            error = null;
            if (raw is string s)
            {
                s = s.Trim();
                if (s.StartsWith("#")) s = s.Substring(1);
                if (s.Length == 6 || s.Length == 8)
                {
                    try
                    {
                        byte r = Convert.ToByte(s.Substring(0, 2), 16);
                        byte g = Convert.ToByte(s.Substring(2, 2), 16);
                        byte b = Convert.ToByte(s.Substring(4, 2), 16);
                        byte a = (s.Length == 8) ? Convert.ToByte(s.Substring(6, 2), 16) : (byte)255;
                        color = new Color32(r, g, b, a);
                        return true;
                    }
                    catch (Exception ex)
                    {
                        error = $"Hex color parse failed: {ex.Message}";
                        return false;
                    }
                }
                error = $"Hex color must be #RRGGBB or #RRGGBBAA; got '{s}'.";
                return false;
            }
            if (raw is List<object> arr && (arr.Count == 3 || arr.Count == 4))
            {
                color = new Color(
                    ToFloat(arr[0]),
                    ToFloat(arr[1]),
                    ToFloat(arr[2]),
                    arr.Count == 4 ? ToFloat(arr[3]) : 1f);
                return true;
            }
            error = "backgroundColor must be a hex string (#RRGGBB or #RRGGBBAA) or an RGB(A) array of 0..1 floats.";
            return false;
        }

        static float ToFloat(object o)
        {
            if (o is double d) return (float)d;
            if (o is float f) return f;
            if (o is long l) return l;
            if (o is int i) return i;
            return 0f;
        }

        static Vector3 AngleToCameraDir(string angle)
        {
            switch ((angle ?? "iso").Trim().ToLowerInvariant())
            {
                case "front":   return Quaternion.Euler(0f, 0f, 0f) * Vector3.back;
                case "back":    return Quaternion.Euler(0f, 180f, 0f) * Vector3.back;
                case "side":
                case "right":   return Quaternion.Euler(0f, 90f, 0f) * Vector3.back;
                case "left":    return Quaternion.Euler(0f, -90f, 0f) * Vector3.back;
                case "top":     return Quaternion.Euler(89f, 0f, 0f) * Vector3.back;
                case "bottom":  return Quaternion.Euler(-89f, 0f, 0f) * Vector3.back;
                case "iso":
                default:        return Quaternion.Euler(20f, -30f, 0f) * Vector3.back;
            }
        }
    }
}
